/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ub.info.prog2.FrancoOriolGubauClara.vista;

import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import ub.info.prog2.FrancoOriolGubauClara.controlador.Controlador;
/**
 *
 * @author Oriol Franco i Clara Gubau
 */
public class AppMercatUB extends javax.swing.JFrame {
    Controlador controlador;
    /**
     * Creates new form AppMercatUB
     */
    public AppMercatUB() {
        initComponents();
        this.controlador = new Controlador();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlMercatUB = new javax.swing.JPanel();
        btnGestioArticles = new javax.swing.JButton();
        btnGestioComandes = new javax.swing.JButton();
        btnGestioClients = new javax.swing.JButton();
        etBenvingudaMercatUB = new javax.swing.JLabel();
        mnbBarraMenu = new javax.swing.JMenuBar();
        mnArxius = new javax.swing.JMenu();
        itmnCarregarFitxer = new javax.swing.JMenuItem();
        itmnGuardarFitxer = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlMercatUB.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255)), "Mercat UB", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(0, 0, 0))); // NOI18N

        btnGestioArticles.setBackground(new java.awt.Color(204, 255, 204));
        btnGestioArticles.setText("Gestionar Articles");
        btnGestioArticles.setToolTipText("");
        btnGestioArticles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGestioArticlesActionPerformed(evt);
            }
        });

        btnGestioComandes.setBackground(new java.awt.Color(204, 255, 255));
        btnGestioComandes.setText("Gestionar Comandes");
        btnGestioComandes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGestioComandesActionPerformed(evt);
            }
        });

        btnGestioClients.setBackground(new java.awt.Color(204, 204, 255));
        btnGestioClients.setText("Gestionar Clients");
        btnGestioClients.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGestioClientsActionPerformed(evt);
            }
        });

        etBenvingudaMercatUB.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        etBenvingudaMercatUB.setForeground(new java.awt.Color(0, 0, 0));
        etBenvingudaMercatUB.setText("Benvinguts a Mercat UB. Seleccioneu una opció:");

        javax.swing.GroupLayout pnlMercatUBLayout = new javax.swing.GroupLayout(pnlMercatUB);
        pnlMercatUB.setLayout(pnlMercatUBLayout);
        pnlMercatUBLayout.setHorizontalGroup(
            pnlMercatUBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMercatUBLayout.createSequentialGroup()
                .addContainerGap(214, Short.MAX_VALUE)
                .addGroup(pnlMercatUBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnGestioClients, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGestioArticles, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGestioComandes, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(205, 205, 205))
            .addGroup(pnlMercatUBLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(etBenvingudaMercatUB, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlMercatUBLayout.setVerticalGroup(
            pnlMercatUBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMercatUBLayout.createSequentialGroup()
                .addComponent(etBenvingudaMercatUB, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(btnGestioArticles)
                .addGap(18, 18, 18)
                .addComponent(btnGestioClients)
                .addGap(18, 18, 18)
                .addComponent(btnGestioComandes)
                .addContainerGap(51, Short.MAX_VALUE))
        );

        mnArxius.setText("Arxius");

        itmnCarregarFitxer.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        itmnCarregarFitxer.setText("Carregar Fitxer");
        itmnCarregarFitxer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmnCarregarFitxerActionPerformed(evt);
            }
        });
        mnArxius.add(itmnCarregarFitxer);

        itmnGuardarFitxer.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        itmnGuardarFitxer.setText("Guardar Fitxer");
        itmnGuardarFitxer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmnGuardarFitxerActionPerformed(evt);
            }
        });
        mnArxius.add(itmnGuardarFitxer);

        mnbBarraMenu.add(mnArxius);

        setJMenuBar(mnbBarraMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(pnlMercatUB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(pnlMercatUB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itmnCarregarFitxerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmnCarregarFitxerActionPerformed
        try {
            JFileChooser fc = new JFileChooser();
            int resultat = fc.showOpenDialog(this);
            if (resultat == JFileChooser.APPROVE_OPTION) {
                controlador.carregarMercat(fc.getSelectedFile().getAbsolutePath());
            }
        }catch (MercatException e) {
            JOptionPane.showMessageDialog(this, e.getMessage(),"", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_itmnCarregarFitxerActionPerformed

    private void itmnGuardarFitxerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmnGuardarFitxerActionPerformed
        try {
            String nomFitxer = JOptionPane.showInputDialog(this, "Introdueixi la ruta per guardar el fitxer","", JOptionPane.DEFAULT_OPTION);
            controlador.guardarMercat(nomFitxer);
        } catch (MercatException e) {
            JOptionPane.showMessageDialog(this, e.getMessage(),"", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_itmnGuardarFitxerActionPerformed

    private void btnGestioClientsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestioClientsActionPerformed
        FrmGestioClients frmGestioClients = new FrmGestioClients(this.controlador);
        frmGestioClients.setTitle("Gestio Clients");
        frmGestioClients.pack();
        frmGestioClients.setVisible(true);
    }//GEN-LAST:event_btnGestioClientsActionPerformed

    private void btnGestioComandesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestioComandesActionPerformed
        FrmGestioComandes frmGestioComandes = new FrmGestioComandes(this.controlador);
        frmGestioComandes.setTitle("Gestio Comandes");
        frmGestioComandes.pack();
        frmGestioComandes.setVisible(true);
    }//GEN-LAST:event_btnGestioComandesActionPerformed

    private void btnGestioArticlesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestioArticlesActionPerformed
        FrmGestioArticles frmGestioArticles = new FrmGestioArticles(this.controlador);
        frmGestioArticles.setTitle("Gestio Articles");
        frmGestioArticles.pack();
        frmGestioArticles.setVisible(true);
    }//GEN-LAST:event_btnGestioArticlesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AppMercatUB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AppMercatUB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AppMercatUB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AppMercatUB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AppMercatUB().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGestioArticles;
    private javax.swing.JButton btnGestioClients;
    private javax.swing.JButton btnGestioComandes;
    private javax.swing.JLabel etBenvingudaMercatUB;
    private javax.swing.JMenuItem itmnCarregarFitxer;
    private javax.swing.JMenuItem itmnGuardarFitxer;
    private javax.swing.JMenu mnArxius;
    private javax.swing.JMenuBar mnbBarraMenu;
    private javax.swing.JPanel pnlMercatUB;
    // End of variables declaration//GEN-END:variables
}
