/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ub.info.prog2.FrancoOriolGubauClara.vista;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import ub.info.prog2.FrancoOriolGubauClara.controlador.Controlador;

/**
 *
 * @author Oriol Franco i Clara Gubau
 */
public class FrmAfegirClient extends javax.swing.JDialog {
    Controlador controlador;
    /**
     * Creates new form FrmAfegirClient
     */
    public FrmAfegirClient(java.awt.Frame parent, boolean modal, Controlador controlador) {
        super(parent, modal);
        this.controlador = controlador;
        initComponents();
        btnAcceptar.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panAfegirClient = new javax.swing.JPanel();
        etNomClient = new javax.swing.JLabel();
        etCorreuElectronic = new javax.swing.JLabel();
        etClientPremium = new javax.swing.JLabel();
        etCognomsClient = new javax.swing.JLabel();
        etAdrecaPostal = new javax.swing.JLabel();
        cbxTipusClient = new javax.swing.JComboBox<>();
        txtAdrecaPostal = new javax.swing.JTextField();
        txtCodiPostal = new javax.swing.JTextField();
        txtNomClient = new javax.swing.JTextField();
        etCodiPostal = new javax.swing.JLabel();
        txtCorreuElectronic = new javax.swing.JTextField();
        txtCognomsClient = new javax.swing.JTextField();
        btnAcceptar = new javax.swing.JButton();
        btnCancellar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        panAfegirClient.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Afegir Client", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        etNomClient.setText("Nom:");

        etCorreuElectronic.setText("Correu electrònic:");

        etClientPremium.setText("Tipus Client:");

        etCognomsClient.setText("Cognoms:");

        etAdrecaPostal.setText("Adreça:");

        cbxTipusClient.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Estàndard", "Prèmium" }));
        cbxTipusClient.setToolTipText("");

        txtAdrecaPostal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtAdrecaPostalKeyReleased(evt);
            }
        });

        txtCodiPostal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCodiPostalKeyReleased(evt);
            }
        });

        txtNomClient.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNomClientKeyReleased(evt);
            }
        });

        etCodiPostal.setText("Codi Postal:");

        txtCorreuElectronic.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCorreuElectronicKeyReleased(evt);
            }
        });

        txtCognomsClient.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCognomsClientKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout panAfegirClientLayout = new javax.swing.GroupLayout(panAfegirClient);
        panAfegirClient.setLayout(panAfegirClientLayout);
        panAfegirClientLayout.setHorizontalGroup(
            panAfegirClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panAfegirClientLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panAfegirClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panAfegirClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(etClientPremium, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(etCorreuElectronic, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(etAdrecaPostal, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(etNomClient))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panAfegirClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(panAfegirClientLayout.createSequentialGroup()
                        .addComponent(txtNomClient, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(etCognomsClient)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCognomsClient))
                    .addGroup(panAfegirClientLayout.createSequentialGroup()
                        .addGroup(panAfegirClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbxTipusClient, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panAfegirClientLayout.createSequentialGroup()
                                .addComponent(txtAdrecaPostal, javax.swing.GroupLayout.PREFERRED_SIZE, 417, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(etCodiPostal)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtCodiPostal, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtCorreuElectronic))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panAfegirClientLayout.setVerticalGroup(
            panAfegirClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panAfegirClientLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panAfegirClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panAfegirClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE, false)
                        .addComponent(etNomClient, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE)
                        .addComponent(etCognomsClient, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtCognomsClient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtNomClient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(panAfegirClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCodiPostal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(etAdrecaPostal, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAdrecaPostal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(etCodiPostal, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panAfegirClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCorreuElectronic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(etCorreuElectronic, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addGroup(panAfegirClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etClientPremium, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxTipusClient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        btnAcceptar.setText("Acceptar");
        btnAcceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAcceptarActionPerformed(evt);
            }
        });

        btnCancellar.setText("Cancel·lar");
        btnCancellar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancellarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAcceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnCancellar, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(panAfegirClient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 12, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panAfegirClient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancellar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAcceptar))
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAcceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAcceptarActionPerformed
        try{
            String nomClient = txtNomClient.getText() + " " + txtCognomsClient.getText();
            String correuElectrClient = txtCorreuElectronic.getText();
            String correuPostalClient = txtAdrecaPostal.getText() + ", " + txtCodiPostal.getText();
            boolean esPremium = ("Prèmium").equals(cbxTipusClient.getSelectedItem());
            controlador.afegirClient(nomClient, correuElectrClient, correuPostalClient, esPremium);
            this.dispose();
        }catch (MercatException e) {
            JOptionPane.showMessageDialog(this, e.getMessage(),"", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnAcceptarActionPerformed

    private void btnCancellarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancellarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancellarActionPerformed

    private void txtNomClientKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNomClientKeyReleased
        btnAcceptar.setEnabled(comprovarTotsCampsPlens());
    }//GEN-LAST:event_txtNomClientKeyReleased

    private void txtCognomsClientKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCognomsClientKeyReleased
        btnAcceptar.setEnabled(comprovarTotsCampsPlens());
    }//GEN-LAST:event_txtCognomsClientKeyReleased

    private void txtAdrecaPostalKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAdrecaPostalKeyReleased
        btnAcceptar.setEnabled(comprovarTotsCampsPlens());
    }//GEN-LAST:event_txtAdrecaPostalKeyReleased

    private void txtCodiPostalKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodiPostalKeyReleased
        btnAcceptar.setEnabled(comprovarTotsCampsPlens());
    }//GEN-LAST:event_txtCodiPostalKeyReleased

    private void txtCorreuElectronicKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCorreuElectronicKeyReleased
        btnAcceptar.setEnabled(comprovarTotsCampsPlens());
    }//GEN-LAST:event_txtCorreuElectronicKeyReleased

   private boolean comprovarCampsPlens(JTextField caixaDeText){
        return !caixaDeText.getText().equals("");
    }
    private boolean comprovarTotsCampsPlens(){
        return comprovarCampsPlens(txtNomClient) && comprovarCampsPlens(txtCognomsClient)
                    && comprovarCampsPlens(txtCorreuElectronic) && comprovarCampsPlens(txtAdrecaPostal)
                    && comprovarCampsPlens(txtCodiPostal);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAcceptar;
    private javax.swing.JButton btnCancellar;
    private javax.swing.JComboBox<String> cbxTipusClient;
    private javax.swing.JLabel etAdrecaPostal;
    private javax.swing.JLabel etClientPremium;
    private javax.swing.JLabel etCodiPostal;
    private javax.swing.JLabel etCognomsClient;
    private javax.swing.JLabel etCorreuElectronic;
    private javax.swing.JLabel etNomClient;
    private javax.swing.JPanel panAfegirClient;
    private javax.swing.JTextField txtAdrecaPostal;
    private javax.swing.JTextField txtCodiPostal;
    private javax.swing.JTextField txtCognomsClient;
    private javax.swing.JTextField txtCorreuElectronic;
    private javax.swing.JTextField txtNomClient;
    // End of variables declaration//GEN-END:variables
}
